apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: engage2-kovaion-com
  namespace: engage
spec:
  secretName: engage3-kovaion-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kovaion-com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - engage1.kovaion.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
