apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pirapp-ingress-dev
  namespace: engage
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "engage1.pirapp.io"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pirapp-api-service-dev
            port:
              number: 8000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: pirapp-auth-service-dev
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pirapp-frontend-service-dev
            port:
              number: 80
  - host: "engage1.kovaion.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pirapp-frontend-service-dev
            port:
              number: 80
  tls:
  - hosts:
    - engage1.kovaion.com
    secretName: engage3-kovaion-com-tls
